project_id = "wojjcelqjnuxmbrbytrt"

[functions.create-payment]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.analyze-audio]
verify_jwt = true